CREATE TABLE EXT_CRMCASE
(
  CRMNUMBER        VARCHAR2(100 BYTE)           NOT NULL,
  POLICYID         NUMBER(19)                   NOT NULL,
  POLICYNUMBER     VARCHAR2(150 BYTE)           NOT NULL,
  MEDIUMANSWER     VARCHAR2(1 BYTE)             NOT NULL,
  STATUS           NUMBER(1)                    DEFAULT 2                     NOT NULL,
  ASSOCIATIONTYPE  NUMBER(1),
  CLAIMID          NUMBER(19),
  CCVID            NUMBER(19),
  HLT_ID           NUMBER(19)
)
;

COMMENT ON TABLE EXT_CRMCASE IS 'Saves CRM Cases to Interfaz, related to tables: AGREGATEDPOLICY, CLAIM, EVALUATEDCOVERAGE, STCL_HISTORYLETTER';

COMMENT ON COLUMN EXT_CRMCASE.CRMNUMBER IS 'PK - CRM Cases, Primary Key';

COMMENT ON COLUMN EXT_CRMCASE.POLICYID IS 'FK - Policy Identifier, Foreign Key, Source Table AGREGATEDPOLICY';

COMMENT ON COLUMN EXT_CRMCASE.POLICYNUMBER IS 'Policy Number';

COMMENT ON COLUMN EXT_CRMCASE.MEDIUMANSWER IS 'Medium Answer, (E) Electronic, (F) Physical';

COMMENT ON COLUMN EXT_CRMCASE.STATUS IS 'Status of CRM Case, RECD_CREATE(2), RECD_UPDATE(3), SENT_OK(4), SENT_ERROR(6), RECD_ERROR(7)';

COMMENT ON COLUMN EXT_CRMCASE.ASSOCIATIONTYPE IS 'Type of Association, 1 (Payment Approve), 2 (Claim Refuse) , 3 (Coverage Refuse), 4 (Requisite Refuse)';

COMMENT ON COLUMN EXT_CRMCASE.CLAIMID IS 'FK - Claim Identifier, Foreign Key, Source Table CLAIM';

COMMENT ON COLUMN EXT_CRMCASE.CCVID IS 'FK - Coverage Identifier, Foreign Key, Source Table EVALUATEDCOVERAGE';

COMMENT ON COLUMN EXT_CRMCASE.HLT_ID IS 'FK - Historical Letter Identifier, Foreign Key, Source Table STCL_HISTORYLETTER';

CREATE UNIQUE INDEX PK_ECRM ON EXT_CRMCASE (CRMNUMBER) LOGGING ;

ALTER TABLE EXT_CRMCASE ADD (
  CONSTRAINT PK_ECRM
  PRIMARY KEY
  (CRMNUMBER)
  USING INDEX PK_ECRM
  ENABLE VALIDATE);

ALTER TABLE EXT_CRMCASE ADD (
  CONSTRAINT FK_ECRM_CCVID FOREIGN KEY (CCVID)
  REFERENCES CONFIGURATEDCOVERAGE (CONFIGURATEDCOVERAGEID)
  ENABLE VALIDATE,
  CONSTRAINT FK_ECRM_CLAIMID FOREIGN KEY (CLAIMID)
  REFERENCES CLAIM (CLAIMID)
  ENABLE VALIDATE,
  CONSTRAINT FK_ECRM_HLTID FOREIGN KEY (HLT_ID)
  REFERENCES STRP_LETTERHISTORY (HLT_ID)
  ENABLE VALIDATE,
  CONSTRAINT FK_ECRM_POLICYID FOREIGN KEY (POLICYID)
  REFERENCES AGREGATEDPOLICY (AGREGATEDPOLICYID)
  ENABLE VALIDATE);

CREATE SEQUENCE SQ_EXT_CRMCASE START WITH 1
MAXVALUE 9999999999999999999999999999
MINVALUE 0 NOCYCLE NOCACHE NOORDER;

INSERT INTO STMA_TABLEINFORMATION VALUES ('EXT_CRMCASE', NULL, 'XECRM', 'EXT', 'Tabla Intermedia de Casos CRM.');
COMMIT;