CREATE TABLE EXT_LOGCRMCASE
(
  ELCRMID         NUMBER(19)                    NOT NULL,
  CRMNUMBER       VARCHAR2(100 BYTE)            NOT NULL,
  MOVEMENTDATE    DATE                          NOT NULL,
  MOVEMENTSTATUS  VARCHAR2(50 BYTE)             NOT NULL,
  JSONIN          CLOB                          NOT NULL,
  JSONOUT         CLOB                          NOT NULL
);

COMMENT ON TABLE EXT_LOGCRMCASE IS 'Saves Log to CRM Cases to Interfaz, related to tables: EXT_CRMCASE';
COMMENT ON COLUMN EXT_LOGCRMCASE.ELCRMID IS 'PK - CRM Cases Log Identifier, Primary Key';
COMMENT ON COLUMN EXT_LOGCRMCASE.CRMNUMBER IS 'FK - CRM Cases, Foreign Key, Source Table EXT_CRMCASE';
COMMENT ON COLUMN EXT_LOGCRMCASE.MOVEMENTDATE IS 'Movement Date';
COMMENT ON COLUMN EXT_LOGCRMCASE.MOVEMENTSTATUS IS 'Movement Status';
COMMENT ON COLUMN EXT_LOGCRMCASE.JSONIN IS 'JSON In of Web Service';
COMMENT ON COLUMN EXT_LOGCRMCASE.JSONOUT IS 'JSON Out of Web Service';

CREATE UNIQUE INDEX PK_ELCRM ON EXT_LOGCRMCASE (ELCRMID) LOGGING;

ALTER TABLE EXT_LOGCRMCASE ADD (
  CONSTRAINT PK_ELCRM
  PRIMARY KEY
  (ELCRMID)
  USING INDEX PK_ELCRM
  ENABLE VALIDATE);

ALTER TABLE EXT_LOGCRMCASE ADD (
  CONSTRAINT FK_ELCRM_CRMNUMBER
  FOREIGN KEY (CRMNUMBER)
  REFERENCES EXT_CRMCASE (CRMNUMBER)
  ENABLE VALIDATE);

INSERT INTO STMA_TABLEINFORMATION VALUES ('EXT_LOGCRMCASE', NULL, 'XELCRM', 'EXT', 'Tabla Log de procesos en la Intermedia de Casos CRM.');
COMMIT;