CREATE TABLE EXT_CRMOPENITEM
(
  CRMNUMBER       VARCHAR2(100 BYTE)            NOT NULL,
  OPMID    NUMBER(19)
);

COMMENT ON TABLE EXT_CRMOPENITEM IS 'Saves Relation between CRM Case and Opentitem, related to tables: EXT_CRM_CASE, OPENITEM';
COMMENT ON COLUMN EXT_CRMOPENITEM.CRMNUMBER IS 'CRM Cases Log Identifier, Primary key, Foreign key, Source Table EXT_CRMCASE';
COMMENT ON COLUMN EXT_CRMOPENITEM.OPMID IS 'Openitem Identifier, Primary key, Foreign key, Source Table OPENITEM';

CREATE UNIQUE INDEX PK_ECRMO ON EXT_CRMOPENITEM (CRMNUMBER,OPMID) LOGGING;

ALTER TABLE EXT_CRMOPENITEM ADD (
  CONSTRAINT PK_ECRMO
  PRIMARY KEY
  (CRMNUMBER,OPMID)
  USING INDEX PK_ECRMO
  ENABLE VALIDATE);

ALTER TABLE EXT_CRMOPENITEM ADD (
  CONSTRAINT FK_ECRMO_CRMNUMBER
  FOREIGN KEY (CRMNUMBER)
  REFERENCES EXT_CRMCASE (CRMNUMBER)
  ENABLE VALIDATE);

ALTER TABLE EXT_CRMOPENITEM ADD (
  CONSTRAINT FK_ECRMO_OPMID
  FOREIGN KEY (OPMID)
  REFERENCES OPENITEM (OPENITEMID)
  ENABLE VALIDATE);

INSERT INTO STMA_TABLEINFORMATION VALUES ('EXT_CRMOPENITEM', 'EXT_CRMOPENITEM', 'ECRMOI', 'CL', 'Saves Relation between CRM Case and Opentitem, related to tables: EXT_CRMCASE, OPENITEM');
COMMIT;